import { notFound } from "next/navigation";
import { getIncident } from "@/lib/incidents/repository";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/utils";

type Props = { params: Promise<{ id: string }> | { id: string } };

export default async function AgreementPage({ params }: Props) {
  const { id } = await params;
  const incident = await getIncident(id);
  const doc = incident?.generatedDocument;
  if (!incident || !doc) notFound();
  const p = doc.payload;

  const signed = Boolean(incident.signature);

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold tracking-tight">{doc.title}</h1>
        <Badge variant={doc.mode === "LIVE" ? "success" : "muted"}>
          {doc.mode === "LIVE" ? "Generated by Doctavian" : "Local render (Doctavian not configured)"}
        </Badge>
      </div>

      {!signed && (
        <div className="rounded-md border border-warning/40 bg-warning/10 px-4 py-2 text-xs font-medium text-foreground">
          PENDING HUMAN SIGNATURE — NOT BINDING. Stamped by Nutrient DWS (or shown here as a banner when
          Nutrient/Doctavian keys are absent). This document has no force until an authorized human signs it.
        </div>
      )}

      <div className="relative space-y-6 overflow-hidden rounded-lg border bg-card p-8 text-sm leading-relaxed">
        {!signed && (
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 flex items-center justify-center select-none"
          >
            <span className="rotate-[-30deg] text-4xl font-black uppercase tracking-widest text-destructive/10">
              Pending Human Signature
            </span>
          </div>
        )}
        <section>
          <h2 className="mb-2 font-semibold">1. Parties</h2>
          <p>
            This Emergency Supplier Transition Agreement (&quot;Agreement&quot;) is entered into by{" "}
            <strong>{p.buyer}</strong> (&quot;Buyer&quot;) and <strong>{p.supplier}</strong> (&quot;Supplier&quot;),
            effective {p.effectiveDate}, in response to disruption {incident.id} affecting {p.product}.
          </p>
        </section>

        <section>
          <h2 className="mb-2 font-semibold">2. Recitals</h2>
          <p>
            The Buyer&apos;s incumbent supplier for {p.product} is unavailable. The AI investigation verified{" "}
            {p.evidenceSummary.verified} claims, identified {p.evidenceSummary.conflicts} unresolved conflict(s), and
            produced a recommendation confidence of {p.evidenceSummary.confidence}%. This Agreement is prepared for
            human authorization; it has no force until signed by an authorized representative of the Buyer.
          </p>
        </section>

        <section>
          <h2 className="mb-2 font-semibold">3. Commercial terms</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>Product: {p.product}</li>
            <li>Quantity: {p.quantity.toLocaleString()} units</li>
            <li>Unit price: {formatCurrency(p.unitPrice)}</li>
            <li>Total value: {formatCurrency(p.totalValue)}</li>
            <li>Delivery deadline: within {p.deliveryDeadlineDays} days of effective date</li>
            <li>SLA: {p.sla}</li>
            <li>Compliance: {p.compliance.join(", ")}</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 font-semibold">4. Risk conditions</h2>
          {p.riskConditions.length > 0 ? (
            <ul className="list-disc space-y-1 pl-5">
              {p.riskConditions.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          ) : (
            <p>No additional risk conditions recorded.</p>
          )}
        </section>

        <section>
          <h2 className="mb-2 font-semibold">5. Contingency</h2>
          <p>{p.contingency}</p>
        </section>

        <section>
          <h2 className="mb-2 font-semibold">6. Signature</h2>
          {incident.signature ? (
            <p>
              Signed by <strong>{incident.signature.signerName}</strong> ({incident.signature.signerTitle}) on{" "}
              {incident.signature.signedAt}.
            </p>
          ) : (
            <p className="text-muted-foreground">Awaiting authorized human signature.</p>
          )}
        </section>
      </div>
    </div>
  );
}